#!/bin/bash

notify-send 'Updating OneDrive, wait a second.' 'Javier Ramírez' -i ~/Icons/Onedrive.ico 

nautilus ~/OneDrive

onedrive --synchronize

notify-send 'OneDrive update complete' 'Javier Ramírez' -i ~/kr4k3n12301/Downloads/Icons/Onedrive.ico
