#!/bin/bash

SPTH="$(find ~/ | grep "Onedrive.ico")"

notify-send 'Updating OneDrive, wait a second.' 'Javier Ramírez' -i $SPTH

xdg-open ~/OneDrive

onedrive --synchronize

notify-send 'OneDrive update complete' 'Javier Ramírez' -i $SPTH
